name: CI
on:
    - pull_request
jobs:
    e2eTesting:
        runs-on: ubuntu-latest
        name: E2E Testing
        steps:
            - uses: actions/checkout@v3
            - name: Start minikube
              uses: medyagh/setup-minikube@master
            - name: Install Nix Package Manager
              uses: cachix/install-nix-action@v18
              with:
                  nix_path: nixpkgs=channel:nixos-22.05
            - name: Deploy to minikube
              run: nix-shell --command "make -f ./commands.nixwrap startE2EServicesCI"
            - name: Install
              run: nix-shell --command "make -f ./commands.nixwrap install"
            - name: Local Publish
              run: nix-shell --command "make -f ./commands.nixwrap localPublish"
            - name: E2E Testing
              run: |
                  nix-shell --command "make -f ./commands.nixwrap installForE2ETesting"
                  nix-shell --command "make -f ./commands.nixwrap e2eTesting"
    unitTesting:
        runs-on: ubuntu-latest
        name: Unit Testing
        steps:
            - uses: actions/checkout@v3
            - name: Install Nix Package Manager
              uses: cachix/install-nix-action@v18
              with:
                  nix_path: nixpkgs=channel:nixos-22.05
            - name: Install & Bootstrap
              run: nix-shell --command "make -f ./commands.nixwrap bootstrap"
            - name: Build
              run: nix-shell --command "make -f ./commands.nixwrap build"
            - name: Unit Testing
              run: nix-shell --command "make -f ./commands.nixwrap unitTesting"
    integrationTesting:
        runs-on: ubuntu-latest
        name: Integration Testing
        steps:
            - uses: actions/checkout@v3
            - name: Start minikube
              uses: medyagh/setup-minikube@master
            - name: Install Nix Package Manager
              uses: cachix/install-nix-action@v18
              with:
                  nix_path: nixpkgs=channel:nixos-22.05
            - name: Deploy to minikube
              run: nix-shell --command "make -f ./commands.nixwrap startIntegrationServicesCI"
            - name: Test service URLs
              run: |
                sleep 10
                minikube service list
                kubectl get pods --namespace default
                kubectl get pods --namespace kube-system
                kubectl logs redis4 -c redis4
                kubectl get pods redis4 -o jsonpath='{.spec.containers[*]}'
                nix-shell --command "redis-cli -p 9004 ping"
            - name: Install & Bootstrap
              run: nix-shell --command "make -f ./commands.nixwrap bootstrap"
            - name: Build
              run: nix-shell --command "make -f ./commands.nixwrap build"
            - name: Integration Testing
              run: nix-shell --command "make -f ./commands.nixwrap integrationTesting"
